[package]
name = "use zkemail"
author = "rajesh"
version = "0.1.0"
compiler_version = ">=0.35.0"

[dependencies]
zkemail = { tag = "v0.3.1", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }